import type { Metadata } from "next";
import Fonts from "../fonts";
import "./globals.css";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={clsx(Fonts.inconsolata.variable, Fonts.inter.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
